work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:llama2_70B-pretrain-profile-fixB}
workspace: ${PRIMUS_WORKSPACE:./output}

modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml
    model: llama2_70B.yaml
    overrides:
      # log
      disable_wandb: true
      disable_tensorboard: true
      stderr_sink_level: INFO

      log_avg_skip_iterations: 2
      log_avg_reset_interval: 50

      train_iters: 15
      micro_batch_size: 1
      global_batch_size: 8

      seq_length: 4096
      max_position_embeddings: 4096

      lr: 1.0e-5
      min_lr: 0.0
      lr_warmup_iters: 2
      lr_decay_iters: null
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6

      # parallel
      tensor_model_parallel_size: 1
      pipeline_model_parallel_size: 1
      expert_model_parallel_size: 1
      overlap_grad_reduce: true

      # data
      mock_data: true
      train_data_path: null
      valid_data_path: null
      test_data_path: null

      # ckpt
      finetune: false
      auto_continue_train: false
      load: null
      save: null
      save_interval: 20000
      disable_last_saving: true

      use_torch_fsdp2: true
      use_distributed_optimizer: false
      overlap_param_gather: false
      gradient_accumulation_fusion: false
      ckpt_format: torch_dist
      sequence_parallel: 1

      # recompute
      recompute_granularity: full
      recompute_method: block
      recompute_num_layers: 80

      # Fix B: use primus-turbo linear layers + Triton GEMM
      enable_primus_turbo: true
      use_turbo_attention: false
      use_turbo_parallel_linear: true
      use_turbo_grouped_mlp: false

      # Cross entropy
      cross_entropy_fusion_impl: "te"
      cross_entropy_loss_fusion: true

      # Fix: reduce GPU-CPU sync overhead
      check_for_nan_in_loss_and_grad: false

      # Profiling
      profile: true
      use_pytorch_profiler: true
      profile_ranks: [0]
      profile_step_start: 8
      profile_step_end: 11

      # Local tokenizer
      tokenizer_model: /home/xiaompen/_Primus-dev/data/huggingface/hub/models--meta-llama--Llama-2-7b-hf/snapshots/01c7f73d771dfac7d292323805ebc428287df4f9
