work_group: ${TEAM:amd}
user_name: ${USER:root}
exp_name: ${EXP_NAME:llama3_405B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: torchtitan
    config: pre_trainer.yaml

    # model to run
    model: llama3.1_405B-fp8.yaml
    overrides:
      sink_level: null
      file_sink_level: DEBUG
      stderr_sink_level: INFO

      training:
        batch_size: 2
        compile: true
        steps: 30
      
      # profiling:
      #   profile_freq: 6

      metrics:
        log_freq: 1

      optimizer:
        lr: 8e-5

      parallelism:
        tensor_parallel_degree: 1

      activation_checkpoint:
        mode: selective
        selective_ac_option: -16 

      primus_turbo:
        enable_primus_turbo: true
        use_turbo_attention: true
        enable_attention_float8: false

      float8:
        enable_fsdp_float8_all_gather: true
        precompute_float8_dynamic_scale_for_fsdp: true
        force_recompute_fp8_weight_in_bwd: true
        filter_fqns: ["output"]