work_group: ${TEAM:amd}
user_name: ${USER:root}
exp_name: ${EXP_NAME:llama3_8B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: torchtitan
    config: pre_trainer.yaml

    # model to run
    model: llama3.1_8B.yaml
    overrides:
      sink_level: null
      file_sink_level: DEBUG
      stderr_sink_level: INFO

      metrics:
        log_freq: 10
        enable_wandb: false

      lr_scheduler:
        # lr scheduler warm up
        warmup_steps: 10

      training:
        batch_size: 3
        compile: true
        steps: 50

      activation_checkpoint:
        mode: "none"  # ["none", "selective", "full"]
        selective_ac_option: "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

      primus_turbo:
        enable_primus_turbo: true
        enable_attention_float8: false
