work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:llama3.1_405B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: torchtitan
    config: pre_trainer.yaml

    # model to run
    model: llama3.1_405B.yaml
    overrides:
      sink_level: null
      file_sink_level: DEBUG
      stderr_sink_level: INFO

      training:
        local_batch_size: 2


      optimizer:
        lr: 8e-5

      parallelism:
        tensor_parallel_degree: 8

      activation_checkpoint:
        mode: full

      primus_turbo:
        enable_primus_turbo: false
        enable_attention_float8: false
