#!/bin/bash

set -euo pipefail

export PRIMUS_TOTAL_LAYERS=${PRIMUS_TOTAL_LAYERS:-43}
export PRIMUS_NUM_EXPERTS=${PRIMUS_NUM_EXPERTS:-256}
export PRIMUS_MOE_TOPK=${PRIMUS_MOE_TOPK:-6}
export PRIMUS_MOE_FFN_HIDDEN_SIZE=${PRIMUS_MOE_FFN_HIDDEN_SIZE:-2048}
export PRIMUS_INDEX_TOPK=${PRIMUS_INDEX_TOPK:-512}
export PRIMUS_COMPRESS_RATIOS=${PRIMUS_COMPRESS_RATIOS:-'"[0, 0, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 128, 4, 0]"'}
export MTP_NUM_LAYERS=${MTP_NUM_LAYERS:-1}

# export NNODES=8
# export PRIMUS_TP=${PRIMUS_TP:-1}
# export PRIMUS_PP=${PRIMUS_PP:-8}
# export PRIMUS_EP=${PRIMUS_EP:-8}
# export PRIMUS_RECOMPUTE_LAYERS=0
# if [ "$MTP_NUM_LAYERS" -eq 1 ]; then
#   export PRIMUS_PP_LAYOUT='"Et*4|t*5|(t*6|)*5,t*4mL"'
# else
#   export PRIMUS_PP_LAYOUT='"Et*4|t*5|(t*6|)*5,t*4L"'
# fi

export NNODES=4
export PRIMUS_TP=${PRIMUS_TP:-1}
export PRIMUS_PP=${PRIMUS_PP:-4}
export PRIMUS_EP=${PRIMUS_EP:-8}
export PRIMUS_RECOMPUTE_LAYERS=3
if [ "$MTP_NUM_LAYERS" -eq 1 ]; then
  export PRIMUS_PP_LAYOUT='"Et*10|t*11|t*11|t*11mL"'
else
  export PRIMUS_PP_LAYOUT='"Et*10|t*11|t*11|t*11L"'
fi

export SLURM_NODELIST=${SLURM_NODELIST:-"smci355-ccs-aus-n04-21,smci355-ccs-aus-n04-25,smci355-ccs-aus-n04-29,smci355-ccs-aus-n04-33,smci355-ccs-aus-n05-21,smci355-ccs-aus-n05-29,smci355-ccs-aus-n05-33"}

export MBS=${MBS:-1}
export GBS=${GBS:-$((64 * NNODES * MBS))}
export TRAIN_ITERS=${TRAIN_ITERS:-10}

export PRIMUS_SEQ_LENGTH=${PRIMUS_SEQ_LENGTH:-4096}
export PRIMUS_MAX_POSITION_EMBEDDINGS=${PRIMUS_MAX_POSITION_EMBEDDINGS:-${PRIMUS_SEQ_LENGTH}}

export USE_V4_FP8_INDEXER=${USE_V4_FP8_INDEXER:-True}
export USE_V4_TRITON_ATTENTION=${USE_V4_TRITON_ATTENTION:-True}
export USE_V4_TRITON_CSA_ATTENTION=${USE_V4_TRITON_CSA_ATTENTION:-True}
export USE_TURBO_DEEPEP=${USE_TURBO_DEEPEP:-True}
export TURBO_USE_GROUPED_MLP=${TURBO_USE_GROUPED_MLP:-True}
export USE_V4_COMPILED_SINKHORN=${USE_V4_COMPILED_SINKHORN:-True}
export USE_TURBO_ATTENTION=${USE_TURBO_ATTENTION:-False}
export PRIMUS_V4_ATTN_BWD_USE_SPLIT=${PRIMUS_V4_ATTN_BWD_USE_SPLIT:-1}
export PRIMUS_V4_CSA_BWD_SEGREDUCE=${PRIMUS_V4_CSA_BWD_SEGREDUCE:-1}
export PRIMUS_STACK_GROUPED_WEIGHT_TRITON=${PRIMUS_STACK_GROUPED_WEIGHT_TRITON:-1}
export PRIMUS_ROPE_TRITON=${PRIMUS_ROPE_TRITON:-1}
export PRIMUS_SINKHORN_TRITON=${PRIMUS_SINKHORN_TRITON:-1}
export PRIMUS_HC_TRITON=${PRIMUS_HC_TRITON:-1}
export PRIMUS_INDEXER_TRITON=${PRIMUS_INDEXER_TRITON:-1}
export PRIMUS_INDEXER_TRITON_FULL=${PRIMUS_INDEXER_TRITON_FULL:-0}
export PRIMUS_V4_ROUTER_TRITON=${PRIMUS_V4_ROUTER_TRITON:-1}
export PROFILE=${PROFILE:-False}
export PRIMUS_EXP_NAME=${PRIMUS_EXP_NAME:-deepseek_v4_flash_proxy_pp${PRIMUS_PP}_ep${PRIMUS_EP}_seq${PRIMUS_SEQ_LENGTH}}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "${SCRIPT_DIR}/run_deepseek_v4.sh"
