bases:
  - deepseek_v2_base.yaml

tokenizer_type: DeepSeekV2Tokenizer
tokenizer_model: deepseek-ai/DeepSeek-V2

multi_latent_attention: false
apply_rope_fusion: true

# model
num_layers: 24
hidden_size: 2048
ffn_hidden_size: 10944
num_attention_heads: 16

qk_head_dim: 128
v_head_dim: 128

# moe
moe_layer_freq: "([0]*0+[1]*24)"
num_experts: 64
# num_shared_experts: 2
moe_ffn_hidden_size: 1408 # moe_intermediate_size
moe_shared_expert_intermediate_size: 2816 # num_shared_experts * moe_ffn_hidden_size

# device limited routing
expert_model_parallel_size: 8
moe_router_num_groups: null # int
moe_router_group_topk: null # int
moe_router_topk_scaling_factor: 1.0 # float
