bases:
  - deepseek_v3_base.yaml

# 45B total params, 3B active params

tokenizer_type: null
extra_tokenizer_type: DeepSeekV3Tokenizer
tokenizer_model: deepseek-ai/DeepSeek-V3

# model
num_layers: 32
hidden_size: 3072
ffn_hidden_size: 7680
num_attention_heads: 40
# mla
q_lora_rank: null
kv_lora_rank: 512
qk_head_dim: 128
qk_pos_emb_head_dim: 64
v_head_dim: 128
kv_channels: 128
# moe
moe_layer_freq: 2
num_experts: 96
moe_router_topk: 4
# num_shared_experts: 1
moe_ffn_hidden_size: 1536
moe_shared_expert_intermediate_size: 1536 # num_shared_experts * moe_ffn_hidden_size

# parallel and optimization
expert_model_parallel_size: 8
moe_router_num_groups: 8 # int
moe_router_group_topk: 3 # int
