bases:
  - language_model.yaml

group_query_attention: false
num_query_groups: null

swiglu: true
add_bias_linear: false
attention_softmax_in_fp32: true
untie_embeddings_and_output_weights: true
hidden_dropout: 0.0
attention_dropout: 0.0

position_embedding_type: rope
rotary_base: 10000
rotary_scaling_factor: 40

normalization: RMSNorm
