bases:
  - llama2_base.yaml

tokenizer_type: Llama2Tokenizer
tokenizer_model: meta-llama/Llama-2-7b-hf

ffn_hidden_size: 28672
hidden_size: 8192
num_attention_heads: 64
num_layers: 80

group_query_attention: true
num_query_groups: 8
