bases:
  - llama3_base.yaml

tokenizer_type: Llama3Tokenizer
tokenizer_model: meta-llama/Meta-Llama-3-70B

ffn_hidden_size: 28672
hidden_size: 8192
num_attention_heads: 64
num_layers: 80
num_query_groups: 8
