bases:
  - llama_base.yaml

init_method_std: 0.01
rotary_base: 500000
qk_layernorm: true

group_query_attention: true
num_query_groups: 8

# moe parameters
moe_router_topk: 1
# moe_router_pre_softmax needs to be set to be true for moe_router_topk=1
moe_router_pre_softmax: true
moe_layer_freq: 1
moe_router_load_balancing_type: aux_loss
moe_aux_loss_coeff: 0.001 
moe_grouped_gemm: true
moe_use_legacy_grouped_gemm: false
moe_token_dispatcher_type: alltoall


