
disable_primus_topk_router: false
moe_router_force_load_balancing: false
use_deprecated_20241209_moe_layer: false

# softcapping for logits (for x.ai grok2)
final_logit_softcapping: null # float
attn_logit_softcapping: null # float
router_logit_softcapping: null # float

# LFM2 model configuration
# lfm_layer_types: ["conv", "conv", "full_attention", "conv", "conv", "conv", "full_attention", "conv", "conv", "conv", "full_attention", "conv", "conv", "conv", "full_attention", "conv", "conv", "conv", "full_attention", "conv", "conv", "full_attention", "conv", "conv"]
lfm_layer_types: null # list[str]
conv_L_cache: 3 # int
conv_bias: false # bool


# Primus patch option
# Control the force load balancing type for the MoE router.
# If set to "even", the router will force the load balancing to be even.
# If set to "uniform", the router will force the load balancing to be uniform. (Megatron-LM original behavior)
moe_router_force_load_balancing_type: "even"
