
disable_primus_topk_router: false
moe_router_force_load_balancing: false
use_deprecated_20241209_moe_layer: false
moe_use_fused_router_with_aux_score: false
fused_padded_mla_attention: false

window_size: null
use_hybrid_sliding_window_attention: false
use_attention_with_yarn: false # set to true to use attention with yarn
rope_type: yarn # rope parameters
beta_slow: 1.0 # yarn parameters
beta_fast: 32.0 # yarn parameters
original_max_position_embeddings: 4096 # yarn parameters
