bases:
  - qwen2.5_base.yaml

tokenizer_type: HuggingFaceTokenizer
tokenizer_model: Qwen/Qwen2.5-72B

# Qwen 2.5 72B specific parameters
hidden_size: 8192
ffn_hidden_size: 29568
num_layers: 80
num_attention_heads: 64
num_query_groups: 8
