work_group: ${TEAM:amd}
user_name: ${USER:root}
exp_name: &exp_name ${EXP:exp-deepseek-pretrain}
workspace: ./output

platform:
  config: platform_azure.yaml
  overrides:
    master_sink_level: INFO

modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml
    model: ${MODEL_CONFIG:deepseek_v2_lite}.yaml
    overrides:
      # log
      wandb_project: "Primus_DeepSeek_Pretrain"
      # disable_wandb: false
      # disable_tensorboard: false
      stderr_sink_level: DEBUG

      # debug
      # num_layers: 5
      # optimizer: adam
      moe_router_force_load_balancing: true
      moe_router_dtype: fp32
      log_avg_skip_iterations: 2
      log_avg_reset_interval: 5

      # recompute
      recompute_granularity: ${RECOMPUTE_GRANULARITY:null} # full, selective
      recompute_method: ${RECOMPUTE_METHOD:null} # uniform, block
      recompute_num_layers: ${RECOMPUTE_NUM_LAYERS:null} # int

      # hyber parameters
      train_iters: ${ITERS:3}
      micro_batch_size: ${MBS:1}
      global_batch_size: ${GBS:64}
      seq_length: ${SEQ_LENGTH:4096}
      max_position_embeddings: ${SEQ_LENGTH:4096}
      lr: 1.0e-5
      min_lr: 0.0
      lr_warmup_iters: 2
      lr_decay_iters: null
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6

      # parallel
      tensor_model_parallel_size: ${TP:1}
      pipeline_model_parallel_size: ${PP:1}
      expert_model_parallel_size: ${EP:1}
      use_torch_fsdp2: true
      use_distributed_optimizer: false
      overlap_param_gather: false

      # data
      train_data_path: ${TOKENIZED_DATA_PATH:null}
      valid_data_path: null
      test_data_path: null

      # fusion
      # 20250321: need latest megatron docker image
      moe_permute_fusion: false
      # 20250317: need latest apex in docker image
      gradient_accumulation_fusion: false
      # 20250317: TE grouped gemm has numerical issue
      moe_use_legacy_grouped_gemm: true

      apply_rope_fusion: false

      # ckpt
      finetune: false
      auto_continue_train: true
      load: null
      no_load_optim: null
      no_load_rng: null
      save: null
      save_interval: 20000
      no_save_optim: null
      no_save_rng: null
      disable_last_saving: true
      ckpt_format: torch_dist
