work_group: amd
user_name: xiaoming
exp_name: exp_pretrain
workspace: ./output

modules:
  # - name: gemm_bench
  #   module: benchmark_gemm
  #   dtype: bf16
  #   shapes: "llama2_7B"
  #   a.b: 1

  - name: pretrain_stage
    module: pretrain
    framework: megatron
    model: llama2_7B
    params:
      global_batch_size: 256
      micro_batch_size: 4
      train_iters: 50
      eval_iters: 0
      stderr_sink_level: DEBUG

