#!/usr/bin/env bash

export NNODES=1
export GPUS_PER_NODE=8
export DP_REPLICATE=1
export LOCAL_BATCH_SIZE=32
export GRADIENT_ACCUMULATION_STEPS=4
export GLOBAL_BATCH_SIZE=1024
export LR=0.00025
export WARMUP_STEPS=800
export GRADIENT_CHECKPOINTING_RATIO=0
export FSDP2_REDUCE_DTYPE=bf16
