#!/usr/bin/env bash

export NNODES=1
export GPUS_PER_NODE=8
export DP_REPLICATE=1
export LOCAL_BATCH_SIZE=64
export GRADIENT_ACCUMULATION_STEPS=1
export GLOBAL_BATCH_SIZE=512
export LR=2e-4
export WARMUP_STEPS=1600
export GRADIENT_CHECKPOINTING_RATIO=0.25
export FSDP2_REDUCE_DTYPE=fp32
