
export ANP_HOME_DIR=${ANP_HOME_DIR:-"/opt/amd-anp"}
export RCCL_HOME_DIR=${RCCL_HOME_DIR:-"/opt/rccl"}
export MPI_HOME_DIR=${MPI_HOME_DIR:-"/opt/ompi-4.1.6"}

LOG_INFO_RANK0 "Using AINIC"
LOG_INFO_RANK0 "RCCL_HOME_DIR: $RCCL_HOME_DIR"
LOG_INFO_RANK0 "ANP_HOME_DIR: $ANP_HOME_DIR"
LOG_INFO_RANK0 "MPI_HOME_DIR: $MPI_HOME_DIR"

export NCCL_IB_TC=${NCCL_IB_TC:-104}
export NCCL_IB_FIFO_TC=${NCCL_IB_FIFO_TC:-184} # 192

export NCCL_IB_GID_INDEX=1
export NCCL_IB_ROCE_VERSION_NUM=2
export NCCL_MAX_P2P_CHANNELS=56
export NET_OPTIONAL_RECV_COMPLETION=1
export NCCL_IB_USE_INLINE=1
export RCCL_GDR_FLUSH_GPU_MEM_NO_RELAXED_ORDERING=0
export NCCL_GDR_FLUSH_DISABLE=1
export NCCL_DMABUF_ENABLE=0
export NCCL_IGNORE_CPU_AFFINITY=1
export NCCL_IB_QPS_PER_CONNECTION=1

export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/libibverbs:${RCCL_HOME_DIR}/build/release:${ANP_HOME_DIR}/build:${MPI_HOME_DIR}/install/lib:$LD_LIBRARY_PATH