// !!! This is a file automatically generated by hipify!!!
/*
 * hipBLASLt FP8 Grouped GEMM for MoE Expert Computation on AMD MI355X.
 *
 * Batches all E expert GEMMs into a SINGLE hipBLASLt GroupedGemm launch,
 * eliminating per-expert Python dispatch overhead.
 *
 * Layout convention (matching PyTorch _scaled_mm on ROCm):
 *   All PyTorch tensors are row-major.  hipBLASLt uses column-major.
 *   Row-major [M, K] = col-major [K, M] with ld = K.
 *
 *   To compute D_row[M, N] = A_row[M, K] × B_row[K, N]:
 *     hipA = B_row data → col-major [N, K], opA = OP_T → op(A) = [K, N]^T? No.
 *
 *   Correct mapping (verified against PyTorch _scaled_mm source):
 *     opA = OP_T, opB = OP_N
 *     hipA = W data [N, K] contiguous → col-major [K, N] → OP_T → [N, K]
 *            m_hip = N, k_hip = K, lda = K
 *     hipB = A data [m, K] contiguous → col-major [K, m] → OP_N → [K, m]
 *            k_hip = K, n_hip = m, ldb = K
 *     D = output [m, N] contiguous → col-major [N, m], ldd = N
 *
 * Build: torch.utils.cpp_extension.load(...)
 */

#include <torch/extension.h>
#include <ATen/hip/HIPContext.h>

#include <hipblaslt/hipblaslt.h>
#include <hipblaslt/hipblaslt-ext.hpp>

#include <vector>
#include <stdexcept>
#include <string>

#define CHECK_HIPBLASLT(cmd)                                                \
  do {                                                                      \
    hipblasStatus_t st = (cmd);                                             \
    if (st != HIPBLAS_STATUS_SUCCESS) {                                     \
      throw std::runtime_error(                                             \
          std::string("hipBLASLt error code ") + std::to_string((int)st) +  \
          " at " + __FILE__ + ":" + std::to_string(__LINE__));              \
    }                                                                       \
  } while (0)

namespace {

hipblasLtHandle_t get_handle() {
  static hipblasLtHandle_t h = nullptr;
  if (!h) CHECK_HIPBLASLT(hipblasLtCreate(&h));
  return h;
}

static thread_local torch::Tensor g_workspace;
static constexpr size_t WORKSPACE_BYTES = 128 * 1024 * 1024;

void* get_workspace(torch::Device dev) {
  if (!g_workspace.defined() || g_workspace.device() != dev) {
    g_workspace = torch::empty({(int64_t)WORKSPACE_BYTES},
        torch::TensorOptions().dtype(torch::kUInt8).device(dev));
  }
  return g_workspace.data_ptr();
}

}  // namespace


/*
 * FP8 Grouped GEMM Forward.
 *
 *   D[e][m, N] = A_fp8[m, K] @ W_NK[e][N, K]^T   (with FP8 dequant scales)
 *
 *  A_fp8    : [total_M, K]  float8_e4m3fn contiguous
 *  W_fp8_NK : [E, N, K]     float8_e4m3fn contiguous
 *  scale_a  : scalar float32 on GPU (activation inverse scale)
 *  scale_b  : scalar float32 on GPU (weight inverse scale)
 *  tpe      : [E] int64 (tokens per expert, on GPU or CPU)
 *
 * Returns D : [total_M, N] bfloat16
 *
 * hipBLASLt mapping (opA=OP_T, opB=OP_N):
 *   hipA = W_NK[e] data, col-maj [K, N], OP_T → [N, K]  →  m_hip=N, k_hip=K, lda=K
 *   hipB = A data,       col-maj [K, m], OP_N → [K, m]  →  k_hip=K, n_hip=m, ldb=K
 *   hipD = D data,       col-maj [N, m],                    ldd=N
 */
torch::Tensor fp8_grouped_gemm_fwd(
    torch::Tensor A_fp8,
    torch::Tensor W_fp8_NK,
    torch::Tensor scale_a,
    torch::Tensor scale_b,
    torch::Tensor tpe)
{
  TORCH_CHECK(A_fp8.is_contiguous(), "A_fp8 must be contiguous");
  TORCH_CHECK(W_fp8_NK.is_contiguous(), "W_fp8_NK must be contiguous");
  TORCH_CHECK(A_fp8.is_cuda(), "A_fp8 must be on GPU");

  const int64_t E       = W_fp8_NK.size(0);
  const int64_t N       = W_fp8_NK.size(1);
  const int64_t K       = W_fp8_NK.size(2);
  const int64_t total_M = A_fp8.size(0);

  auto D = torch::zeros({total_M, N},
      torch::TensorOptions().dtype(torch::kBFloat16).device(A_fp8.device()));

  auto tpe_cpu = tpe.to(torch::kCPU, torch::kInt64);
  auto* tpe_ptr = tpe_cpu.data_ptr<int64_t>();

  int num_problems = 0;
  for (int64_t e = 0; e < E; e++)
    if (tpe_ptr[e] > 0) num_problems++;
  if (num_problems == 0) return D;

  hipblasLtHandle_t handle = get_handle();
  hipStream_t stream = at::cuda::getCurrentHIPStream().stream();

  hipblaslt_ext::GroupedGemm gg(
      handle,
      HIPBLAS_OP_T,    // opA
      HIPBLAS_OP_N,    // opB
      HIP_R_8F_E4M3,  // typeA (weight W)
      HIP_R_8F_E4M3,  // typeB (activation A)
      HIP_R_16BF,     // typeC
      HIP_R_16BF,     // typeD
      HIPBLAS_COMPUTE_32F);

  std::vector<int64_t> m_vec, n_vec, k_vec, batch_vec;
  std::vector<int64_t> lda_vec, ldb_vec, ldc_vec, ldd_vec;
  std::vector<int64_t> strA_vec, strB_vec, strC_vec, strD_vec;
  std::vector<hipblaslt_ext::GemmEpilogue> epi_vec;
  std::vector<hipblaslt_ext::GemmInputs> inp_vec;

  float alpha_val = 1.0f;
  float beta_val  = 0.0f;

  // hipA = W (weight) → scaleA = weight scale = scale_b
  // hipB = A (activation) → scaleB = activation scale = scale_a
  float* d_scale_a = scale_a.data_ptr<float>();
  float* d_scale_b = scale_b.data_ptr<float>();

  int64_t offset = 0;
  for (int64_t e = 0; e < E; e++) {
    int64_t m_tokens = tpe_ptr[e];
    if (m_tokens <= 0) { offset += 0; continue; }

    m_vec.push_back(N);           // m_hip = N
    n_vec.push_back(m_tokens);    // n_hip = m_tokens
    k_vec.push_back(K);           // k_hip = K
    batch_vec.push_back(1);

    lda_vec.push_back(K);  // hipA = W_NK[e] [N,K] row-maj → col-maj [K,N], lda=K
    ldb_vec.push_back(K);  // hipB = A[s:t] [m,K] row-maj → col-maj [K,m], ldb=K
    ldc_vec.push_back(N);
    ldd_vec.push_back(N);  // D [m,N] row-maj → col-maj [N,m], ldd=N
    strA_vec.push_back(0);
    strB_vec.push_back(0);
    strC_vec.push_back(0);
    strD_vec.push_back(0);

    hipblaslt_ext::GemmEpilogue epi;
    epi.setMode(HIPBLASLT_EPILOGUE_DEFAULT);
    epi_vec.push_back(std::move(epi));

    hipblaslt_ext::GemmInputs inp;
    // hipA = weight data for expert e
    inp.setA(static_cast<const char*>(W_fp8_NK[e].data_ptr()));
    // hipB = activation data for tokens [offset, offset+m)
    inp.setB(static_cast<const char*>(A_fp8.data_ptr()) + offset * K);
    // hipC = hipD = output
    char* d_ptr = static_cast<char*>(D.data_ptr()) + offset * N * 2; // bf16 = 2 bytes
    inp.setC(d_ptr);
    inp.setD(d_ptr);
    inp.setAlpha(&alpha_val);
    inp.setBeta(&beta_val);
    inp.setScaleA(d_scale_b);  // scaleA → weight scale
    inp.setScaleB(d_scale_a);  // scaleB → activation scale
    inp_vec.push_back(std::move(inp));

    offset += m_tokens;
  }

  hipblaslt_ext::GemmProblemType probType(
      HIPBLAS_OP_T, HIPBLAS_OP_N,
      HIP_R_8F_E4M3, HIP_R_8F_E4M3,
      HIP_R_16BF, HIP_R_16BF,
      HIPBLAS_COMPUTE_32F);

  CHECK_HIPBLASLT(gg.setProblem(
      m_vec, n_vec, k_vec, batch_vec,
      lda_vec, ldb_vec, ldc_vec, ldd_vec,
      strA_vec, strB_vec, strC_vec, strD_vec,
      epi_vec, inp_vec, probType));

  hipblaslt_ext::GemmPreference pref;
  pref.setMaxWorkspaceBytes(WORKSPACE_BYTES);

  std::vector<hipblasLtMatmulHeuristicResult_t> results;
  CHECK_HIPBLASLT(gg.algoGetHeuristic(1, pref, results));
  TORCH_CHECK(!results.empty(), "hipBLASLt: no FP8 grouped GEMM FWD algorithm found");

  void* ws = get_workspace(A_fp8.device());
  CHECK_HIPBLASLT(gg.initialize(results[0].algo, ws));
  CHECK_HIPBLASLT(gg.run(stream));

  return D;
}


/*
 * FP8 Grouped GEMM dA backward.
 *
 *   dA[e][m, K] = grad_fp8[m, N] @ W_fp8_KN[e][K, N]^T
 *               = grad_fp8[m, N] × W_NK_eff[N, K]
 *
 * We need: dA = grad @ W_NK where W_NK is [N, K].
 * But we receive W_KN [E, K, N] contiguous.
 *
 * hipBLASLt mapping (opA=OP_T, opB=OP_N):
 *   hipA = W_KN[e] data, col-maj [N, K], OP_T → [K, N]  →  m_hip=K, k_hip=N, lda=N
 *   hipB = grad data,    col-maj [N, m], OP_N → [N, m]  →  k_hip=N, n_hip=m, ldb=N
 *   hipD = dA data,      col-maj [K, m],                    ldd=K
 */
torch::Tensor fp8_grouped_gemm_dA(
    torch::Tensor grad_fp8,
    torch::Tensor W_fp8_KN,   // [E, K, N] contiguous
    torch::Tensor scale_grad,
    torch::Tensor scale_w,
    torch::Tensor tpe)
{
  TORCH_CHECK(grad_fp8.is_contiguous(), "grad_fp8 must be contiguous");
  TORCH_CHECK(W_fp8_KN.is_contiguous(), "W_fp8_KN must be contiguous");

  const int64_t E       = W_fp8_KN.size(0);
  const int64_t K_dim   = W_fp8_KN.size(1);
  const int64_t N_dim   = W_fp8_KN.size(2);
  const int64_t total_M = grad_fp8.size(0);

  auto dA = torch::zeros({total_M, K_dim},
      torch::TensorOptions().dtype(torch::kBFloat16).device(grad_fp8.device()));

  auto tpe_cpu = tpe.to(torch::kCPU, torch::kInt64);
  auto* tpe_ptr = tpe_cpu.data_ptr<int64_t>();

  int num_problems = 0;
  for (int64_t e = 0; e < E; e++)
    if (tpe_ptr[e] > 0) num_problems++;
  if (num_problems == 0) return dA;

  hipblasLtHandle_t handle = get_handle();
  hipStream_t stream = at::cuda::getCurrentHIPStream().stream();

  hipblaslt_ext::GroupedGemm gg(
      handle,
      HIPBLAS_OP_T, HIPBLAS_OP_N,
      HIP_R_8F_E4M3, HIP_R_8F_E4M3,
      HIP_R_16BF, HIP_R_16BF,
      HIPBLAS_COMPUTE_32F);

  std::vector<int64_t> m_vec, n_vec, k_vec, batch_vec;
  std::vector<int64_t> lda_vec, ldb_vec, ldc_vec, ldd_vec;
  std::vector<int64_t> strA_vec, strB_vec, strC_vec, strD_vec;
  std::vector<hipblaslt_ext::GemmEpilogue> epi_vec;
  std::vector<hipblaslt_ext::GemmInputs> inp_vec;

  float alpha_val = 1.0f;
  float beta_val  = 0.0f;
  float* d_scale_grad = scale_grad.data_ptr<float>();
  float* d_scale_w    = scale_w.data_ptr<float>();

  int64_t offset = 0;
  for (int64_t e = 0; e < E; e++) {
    int64_t m_tokens = tpe_ptr[e];
    if (m_tokens <= 0) continue;

    m_vec.push_back(K_dim);        // m_hip = K
    n_vec.push_back(m_tokens);     // n_hip = m_tokens
    k_vec.push_back(N_dim);        // k_hip = N
    batch_vec.push_back(1);

    lda_vec.push_back(N_dim);  // hipA = W_KN[e] [K,N] row → col [N,K], lda=N
    ldb_vec.push_back(N_dim);  // hipB = grad[s:t] [m,N] row → col [N,m], ldb=N
    ldc_vec.push_back(K_dim);
    ldd_vec.push_back(K_dim);  // dA [m,K] row → col [K,m], ldd=K
    strA_vec.push_back(0);
    strB_vec.push_back(0);
    strC_vec.push_back(0);
    strD_vec.push_back(0);

    hipblaslt_ext::GemmEpilogue epi;
    epi.setMode(HIPBLASLT_EPILOGUE_DEFAULT);
    epi_vec.push_back(std::move(epi));

    hipblaslt_ext::GemmInputs inp;
    inp.setA(static_cast<const char*>(W_fp8_KN[e].data_ptr()));
    inp.setB(static_cast<const char*>(grad_fp8.data_ptr()) + offset * N_dim);
    char* da_ptr = static_cast<char*>(dA.data_ptr()) + offset * K_dim * 2;
    inp.setC(da_ptr);
    inp.setD(da_ptr);
    inp.setAlpha(&alpha_val);
    inp.setBeta(&beta_val);
    inp.setScaleA(d_scale_w);     // hipA = weight → weight scale
    inp.setScaleB(d_scale_grad);  // hipB = grad → grad scale
    inp_vec.push_back(std::move(inp));

    offset += m_tokens;
  }

  hipblaslt_ext::GemmProblemType probType(
      HIPBLAS_OP_T, HIPBLAS_OP_N,
      HIP_R_8F_E4M3, HIP_R_8F_E4M3,
      HIP_R_16BF, HIP_R_16BF,
      HIPBLAS_COMPUTE_32F);

  CHECK_HIPBLASLT(gg.setProblem(
      m_vec, n_vec, k_vec, batch_vec,
      lda_vec, ldb_vec, ldc_vec, ldd_vec,
      strA_vec, strB_vec, strC_vec, strD_vec,
      epi_vec, inp_vec, probType));

  hipblaslt_ext::GemmPreference pref;
  pref.setMaxWorkspaceBytes(WORKSPACE_BYTES);

  std::vector<hipblasLtMatmulHeuristicResult_t> results;
  CHECK_HIPBLASLT(gg.algoGetHeuristic(1, pref, results));
  TORCH_CHECK(!results.empty(), "hipBLASLt: no FP8 grouped GEMM dA algorithm found");

  void* ws = get_workspace(grad_fp8.device());
  CHECK_HIPBLASLT(gg.initialize(results[0].algo, ws));
  CHECK_HIPBLASLT(gg.run(stream));

  return dA;
}


PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("fp8_grouped_gemm_fwd", &fp8_grouped_gemm_fwd,
        "FP8 Grouped GEMM Forward (hipBLASLt)");
  m.def("fp8_grouped_gemm_dA", &fp8_grouped_gemm_dA,
        "FP8 Grouped GEMM dA backward (hipBLASLt)");
}
