schema_version: '1.0'
run_id: real_e2e_escape_demo_r1_c1_a8d6ecac
created_at: '2026-05-11T02:18:41+00:00'
cluster_config_ref: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/pilot/cluster.yaml
plan:
  base_ref: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/examples/megatron/configs/MI355X/llama3.2_1B-FP8-pretrain.yaml
  effective_ref: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/pilot/pilot/state/runs/real_e2e_escape_demo_r1_c1_a8d6ecac/plan.effective.yaml
  overrides:
    wandb_project: Primus_Pretrain
    stderr_sink_level: DEBUG
    log_avg_skip_iterations: 2
    log_avg_reset_interval: 50
    train_iters: 12
    micro_batch_size: 4
    global_batch_size: 32
    seq_length: 8192
    max_position_embeddings: 8192
    lr: 1.0e-05
    min_lr: 0.0
    lr_warmup_iters: 2
    lr_decay_iters: null
    lr_decay_style: cosine
    weight_decay: 0.1
    adam_beta1: 0.9
    adam_beta2: 0.95
    eod_mask_loss: true
    init_method_std: 0.008
    norm_epsilon: 1.0e-06
    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    expert_model_parallel_size: 1
    overlap_grad_reduce: true
    overlap_param_gather: true
    gradient_accumulation_fusion: false
    mock_data: true
    train_data_path: null
    valid_data_path: null
    test_data_path: null
    finetune: false
    auto_continue_train: false
    load: null
    no_load_optim: null
    no_load_rng: null
    save: null
    save_interval: 20000
    no_save_optim: null
    no_save_rng: null
    disable_last_saving: true
    ckpt_format: torch
    enable_primus_turbo: true
    use_turbo_attention: false
    use_turbo_grouped_mlp: false
    fp8: hybrid
    moe_use_legacy_grouped_gemm: false
    turbo_deepep_use_comm_stream: true
launch:
  mode: single
  nnodes: 1
  gpus_per_node: 8
  master_addr: 127.0.0.1
  master_port: 34501
  cmd: bash /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/examples/run_pretrain.sh
  env_diff:
    EXP: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/pilot/pilot/state/runs/real_e2e_escape_demo_r1_c1_a8d6ecac/plan.effective.yaml
    NNODES: '1'
    GPUS_PER_NODE: '8'
    MASTER_ADDR: 127.0.0.1
    MASTER_PORT: '34501'
    TRAIN_LOG: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/pilot/pilot/state/runs/real_e2e_escape_demo_r1_c1_a8d6ecac/train.log
    NODE_RANK: '0'
  pid: 15852
  slurm_job_id: null
  slurm_step_id: null
log:
  stdout: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/pilot/pilot/state/runs/real_e2e_escape_demo_r1_c1_a8d6ecac/train.log
  stderr: null
  exit_code_sentinel: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/pilot/pilot/state/runs/real_e2e_escape_demo_r1_c1_a8d6ecac/exit_code.txt
profile:
  enabled: true
  skipped_reason: null
  knobs:
    profile: true
    use_pytorch_profiler: true
    profile_step_start: 5
    profile_step_end: 6
    profile_ranks:
    - 0
    tensorboard_dir: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/pilot/pilot/state/runs/real_e2e_escape_demo_r1_c1_a8d6ecac/profile/tb
    torch_profiler_use_gzip: true
    torch_profiler_record_shapes: false
    torch_profiler_with_stack: false
    disable_profiler_activity_cpu: false
  trace_dir: /shared/amdgpu/home/xiaoming_peng_qle/workspace/Primus/pilot/pilot/state/runs/real_e2e_escape_demo_r1_c1_a8d6ecac/profile/tb
  warnings: []
  train_iters_bumped: false
status: completed
exit_code: 0
wallclock_s: 63.64
