work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:llama3.1_70B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: torchtitan
    config: pre_trainer.yaml

    # model to run
    model: llama3.1_70B.yaml
    overrides:
      sink_level: null
      file_sink_level: DEBUG
      stderr_sink_level: INFO

      lr_scheduler:
        # lr scheduler warm up
        warmup_steps: 10

      metrics:
        log_freq: 10

      training:
        local_batch_size: 4
        steps: 50

      optimizer:
        lr: 1.5e-4

      activation_checkpoint:
        mode: full

      primus_turbo:
        enable_primus_turbo : true
        enable_attention_float8 : false
