job:
  dump_folder: "./outputs"
  description: "DeepSeek-V3 16B model training"
  print_config: false


model:
  name: "deepseek_v3"
  flavor: "16B"
  hf_assets_path: "deepseek-ai/deepseek-moe-16b-base"
  # converters: ["float8"]
