job:
  dump_folder: "./outputs"
  description: "Qwen 3 8B training"

model:
  name: "qwen3"
  flavor: "8B"
  hf_assets_path: "/mnt/vast/araina/Primus/third_party/maxtext/assets/qwen3-tokenizer"
  converters:
    - primus_turbo
