# This is a placeholder model config for hybrid models
# The actual training parameters are specified in the training_command section
# of the experiment config file.

# Model arguments
model_name_or_path: meta-llama/Llama-3.2-1B-Instruct 
teacher_model_name_or_path: meta-llama/Llama-3.1-8B-Instruct 
mamba_ILD_path: checkpoints/Zebra-1B-ILD-M2
mla_ILD_path: checkpoints/Zebra-1B-ILD-MLA 
with_distill: false
mla_layers: [0,5,10,14]
init_with_svd: false
init_with_kqvo: false
decontaminate: true
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
data_ratio: 0.8
chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
dataset_mixer:
  JunxiongWang/sftdatasetv3: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 128

# SFT trainer config
bf16: true
do_eval: true
ILD: false
evaluation_strategy: epoch
factor: 32.0
gradient_accumulation_steps: 2
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 8.0e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
original_max_position_embeddings: 8192
output_dir: checkpoints/Zebra-1B8B-4MLA12M2
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 12
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 2000
save_total_limit: 1
seed: 42
warmup_ratio: 0.01
kl_weight: 1.0
ce_weight: 0.0 

# MLA configs
q_lora_rank: 1344
qk_rope_head_dim: 32
kv_lora_rank: 128
v_head_dim: 64
qk_nope_head_dim: 32
use_lora_layer_norm: false
use_full_kv_head: false
