includes:
  - ../module_base.yaml

lr_scheduler:
  decay_ratio: null
  decay_type: linear
  min_lr_factor: 0.0
  warmup_steps: 200

metrics:
  disable_color_printing: false
  enable_tensorboard: false
  enable_wandb: false
  log_freq: 10
  save_for_all_ranks: false
  save_tb_folder: tb

optimizer:
  beta1: 0.9
  beta2: 0.95
  early_step_in_backward: false
  eps: 1.0e-08
  implementation: fused
  lr: 0.0008
  name: AdamW
  weight_decay: 0.1

profiling:
  enable_memory_snapshot: false
  enable_profiling: false
  profile_freq: 10
  save_memory_snapshot_folder: memory_snapshot
  save_traces_folder: profile_traces

training:
  dataset: c4
  dataset_path: null
  deterministic: false
  enable_cpu_offload: false
  gc_debug: false
  gc_freq: 50
  global_batch_size: -1
  local_batch_size: 8
  max_norm: 1.0
  mixed_precision_param: bfloat16
  mixed_precision_reduce: float32
  seed: null
  seq_len: 2048
  steps: 10000


parallelism:
  context_parallel_degree: 1
  context_parallel_rotate_method: allgather
  data_parallel_replicate_degree: 1
  data_parallel_shard_degree: -1
  disable_loss_parallel: false
  enable_async_tensor_parallel: false
  enable_compiled_autograd: false
  expert_parallel_degree: 1
  expert_tensor_parallel_degree: 1
  fsdp_reshard_after_forward: default
  module_fqns_per_model_part: null
  pipeline_parallel_degree: 1
  pipeline_parallel_first_stage_less_layers: 1
  pipeline_parallel_last_stage_less_layers: 1
  pipeline_parallel_layers_per_stage: null
  pipeline_parallel_microbatch_size: 1
  pipeline_parallel_schedule: 1F1B
  pipeline_parallel_schedule_csv: ''
  pipeline_parallel_split_points: []
  tensor_parallel_degree: 1

checkpoint:
  enable: false
  folder: checkpoint
  interval: 500
  initial_load_path: null
  initial_load_model_only: true
  initial_load_in_hf: false
  last_save_model_only: true
  last_save_in_hf: false
  export_dtype: float32
  async_mode: disabled
  keep_latest_k: 10
  load_step: -1
  exclude_from_loading: []
  enable_first_step_checkpoint: false
  create_seed_checkpoint: false

activation_checkpoint:
  mode: none
  selective_ac_option: "2"
  per_op_sac_force_recompute_mm_shapes_by_fqns:
    - moe.router.gate

compile:
  enable: true
  components:
    - model
    - loss

float8:
  enable_fsdp_float8_all_gather: false
  precompute_float8_dynamic_scale_for_fsdp: false
  recipe_name: null
  filter_fqns: []
  emulate: false
  moe_fqns_prototype: []

mx:
  mxfp8_dim1_cast_kernel_choice: triton
  recipe_name: mxfp8_cublas
  filter_fqns:
    - output
  moe_fqns_prototype: []

comm:
  init_timeout_seconds: 300
  train_timeout_seconds: 100
  trace_buf_size: 20000
  save_traces_folder: comm_traces

memory_estimation:
  enable: false
  disable_fake_mode: false

fault_tolerance:
  enable: false
  process_group: gloo
  process_group_timeout_ms: 10000
  replica_id: 0
  group_size: 0
  min_replica_size: 1
  semi_sync_method: null

experimental:
  custom_import: ""
  custom_args_module : "primus.backends.torchtitan.primus_turbo_extensions.config_extension"

validation:
  enable: false
  dataset: c4_validation
  dataset_path: null
  local_batch_size: 8
  seq_len: 2048
  freq: 10
  steps: -1

primus_turbo:
  enable_primus_turbo : true
  enable_attention_float8 : false
  use_turbo_attention: true
  use_turbo_async_tp: true
  use_turbo_mx_linear: true
