work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:llama3.2_1B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: hybrid_models
    config: pre_trainer.yaml
    model: zebra_llama/llama3.2_1B/zebra_8MLA8M2_8bt_SFT.yaml
    backend_path: Zebra-Llama
    
    # Accelerate launch parameters
    training_command:
      script: train_hybrid/train_distill.py
      accelerate_config: configs/fsdp.yaml
      model_config: configs/llama3.2_1B/zebra_8MLA8M2_8bt_SFT.yaml
      ACCELERATE_LOG_LEVEL: info
    