work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:qwen2.5_7B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml
    # data_path: ./data

    # model to run
    model: qwen2.5_7B.yaml
    overrides:
      # log
      wandb_project: "Primus_Qwen2.5_7B_Pretrain"
      # disable_wandb: false
      # disable_tensorboard: false
      stderr_sink_level: DEBUG

      log_avg_skip_iterations: 2
      log_avg_reset_interval: 50

      train_iters: 50
      micro_batch_size: 10
      global_batch_size: 640

      seq_length: ${PRIMUS_SEQ_LENGTH:2048}
      max_position_embeddings: ${PRIMUS_MAX_POSITION_EMBEDDINGS:131072}

      lr: 1.0e-5
      min_lr: 0.0
      lr_warmup_iters: 2
      lr_decay_iters: 320000
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6

      # parallel
      tensor_model_parallel_size: 1
      pipeline_model_parallel_size: 1
      expert_model_parallel_size: 1
      overlap_grad_reduce: true
      overlap_param_gather: true

      # data
      mock_data: true
      train_data_path: null
      valid_data_path: null
      test_data_path: null

      # ckpt
      finetune: false
      auto_continue_train: ${CONTI_PARAMS:0}
      load: null
      no_load_optim: null
      no_load_rng: null
      save: null
      save_interval: 20000
      no_save_optim: null
      no_save_rng: null
      disable_last_saving: true
      ckpt_format: torch

      gradient_accumulation_fusion: false

      # Turbo
      enable_primus_turbo: true
      use_turbo_attention: true
      use_turbo_grouped_mlp: true

      # Cross entropy flags
      cross_entropy_fusion_impl: "te"
      cross_entropy_loss_fusion: true
