bases:
  - llama_base.yaml

# moe args
moe_grouped_gemm: true
moe_router_load_balancing_type: aux_loss
moe_aux_loss_coeff: ${moe_aux_loss_coeff:0.0}
moe_z_loss_coeff: ${moe_z_loss_coeff:2e-4}
# moe_st_load_balancing_loss_coeff: ${moe_st_load_balancing_loss_coeff:6e-3}
# moe_dp_st_load_balancing_loss_coeff: ${moe_dp_st_load_balancing_loss_coeff:0.0}
# moe_partitioned_ep_st_load_balancing_loss_coeff: ${moe_partitioned_ep_st_load_balancing_loss_coeff:0.0}
