work_group: ${PRIMUS_DATE:amd}
user_name: ${PRIMUS_MODEL_NAME:root}
exp_name: ${PRIMUS_EXP_NAME:deepseek_549B_2M-pretrain.profile}
workspace: ./output

modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml

    # model to run
    model: deepseek_549B_2M.yaml
    overrides:
      # log
      wandb_project: "Primus_DeepSeek_Pretrain"
      stderr_sink_level: DEBUG

      # debug
      # moe_router_force_load_balancing: false
      log_avg_skip_iterations: 2
      log_avg_reset_interval: 50


      # hyber parameters
      train_iters: 10
      micro_batch_size: 1
      global_batch_size: 8
      seq_length: ${PRIMUS_SEQ_LENGTH:4096}
      max_position_embeddings: ${PRIMUS_MAX_POSITION_EMBEDDINGS:4096}
      lr: 1.0e-5
      min_lr: 0.0
      lr_warmup_iters: 2
      lr_decay_iters: null
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6

      # recompute
      # recompute_granularity: full # full, selective
      # recompute_method: block # uniform, block
      # recompute_num_layers: 0 # int

      # recompute
      # recompute_granularity: full # full, selective
      # recompute_method: null # uniform, block
      # recompute_num_layers: 0 # int
      # recompute_layer_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,19, 20,21]

      # parallel
      tensor_model_parallel_size: ${PRIMUS_TP:1}
      pipeline_model_parallel_size: ${PRIMUS_PP:1}
      expert_model_parallel_size: ${PRIMUS_EP:8}
      # num_virtual_stages_per_pipeline_rank: 2
      # num_virtual_stages_per_pipeline_rank: 3
      # for 64 layers
      # decoder_pipeline_manual_split_list: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      # num_virtual_stages_per_pipeline_rank: 4
      # decoder_pipeline_manual_split_list: [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1]
      overlap_grad_reduce: true
      overlap_param_gather: true

      # data
      mock_data: true
      train_data_path: ${TOKENIZED_DATA_PATH:null}
      valid_data_path: null
      test_data_path: null

      profile: true
      use_pytorch_profiler: true
      profile_step_end: 7
      profile_step_start: 6

      # fusion
      # fused wgrad gemm and accumulation
      gradient_accumulation_fusion: true
      # recommend set `false` in fp8
      moe_use_legacy_grouped_gemm: true
      # fused topk router with aux score
      # moe_use_fused_router_with_aux_score: false
      # pad 192/128 for deepseek attention
      fused_padded_mla_attention: false

      # ckpt
      finetune: false
      auto_continue_train: false
      load: null
      no_load_optim: null
      no_load_rng: null
      save: null
      save_interval: 20000
      no_save_optim: null
      no_save_rng: null
      disable_last_saving: true
      ckpt_format: torch
      eval_iters: 0

      # use_precision_aware_optimizer: true
      # main_params_dtype: fp16
      # main_grads_dtype: bf16
      # moe_router_num_groups: 2 # int, node number
      # moe_router_group_topk: 1

      ##################################
      moe_router_force_load_balancing: true
      moe_use_fused_router_with_aux_score: false
      cp_comm_type: a2a
      enable_primus_turbo: true
      use_turbo_attention: true
      use_turbo_grouped_mlp: true

      # use deepep
      moe_token_dispatcher_type: alltoall   #flex   alltoall
      moe_shared_expert_overlap: false
      # moe_enable_deepep: true
      # moe_router_dtype: fp32
      # moe_deepep_num_cus: 64

      moe_permute_fusion: true
