work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:exp-llama3_405B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml
    model: llama3.1_405B.yaml
    overrides:
      # log
      wandb_project: "Primus_Pretrain"
      stderr_sink_level: DEBUG

      log_avg_skip_iterations: 2
      log_avg_reset_interval: 50

      train_iters: 50
      micro_batch_size: 1
      global_batch_size: 256

      seq_length: 8192
      max_position_embeddings: 8192

      lr: 1.0e-5
      min_lr: 0.0
      lr_warmup_iters: 2
      lr_decay_iters: null
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6

      # parallel
      tensor_model_parallel_size: 8
      pipeline_model_parallel_size: 8
      expert_model_parallel_size: 1

      # data
      mock_data: true
      train_data_path: null
      valid_data_path: null
      test_data_path: null

      # ckpt
      finetune: false
      auto_continue_train: false
      load: null
      no_load_optim: null
      no_load_rng: null
      save: null
      save_interval: 20000
      no_save_optim: null
      no_save_rng: null
      disable_last_saving: true

      use_distributed_optimizer: true
      overlap_param_gather: true
      gradient_accumulation_fusion: true
      overlap_grad_reduce: true

      # use_torch_fsdp2: true
      # use_distributed_optimizer: false
      # overlap_param_gather: false
      # ckpt_format: torch_dist
      # sequence_parallel: 1
      # gradient_accumulation_fusion: false

      fp8: hybrid
