work_group: ${TEAM:amd}
user_name: ${USER:root}
exp_name: exp-llama3_405B-pretrain
workspace: ./output

modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml
    model: llama3.1_405B.yaml
    overrides:
      # log
      wandb_project: "Primus_Pretrain"
      stderr_sink_level: DEBUG

      log_avg_skip_iterations: 2
      log_avg_reset_interval: 5

      # profile
      profile: true
      use_pytorch_profiler: true
      profile_step_end: 7
      profile_step_start: 6
      profile_ranks: [0]
      disable_tensorboard: false

      train_iters: ${PRIMUS_TRAIN_ITERS:20}
      micro_batch_size: ${PRIMUS_MBS:1}
      global_batch_size: ${PRIMUS_GBS:256}

      seq_length: ${PRIMUS_SEQ_LENGTH:8192}
      max_position_embeddings: ${PRIMUS_MAX_POSITION_EMBEDDINGS:8192}

      lr: 1.0e-5
      min_lr: 0.0
      lr_warmup_iters: 2
      lr_decay_iters: null
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6

      # parallel
      tensor_model_parallel_size: 2
      pipeline_model_parallel_size: 2 
      expert_model_parallel_size: 1

      # data
      mock_data: true
      train_data_path: ${TOKENIZED_DATA_PATH:null}
      valid_data_path: null
      test_data_path: null

      # ckpt
      finetune: false
      auto_continue_train: false
      load: null
      no_load_optim: null
      no_load_rng: null
      save: null
      save_interval: 20000
      no_save_optim: null
      no_save_rng: null
      disable_last_saving: true

      use_distributed_optimizer: true
      overlap_param_gather: true
      gradient_accumulation_fusion: true
      overlap_grad_reduce: true
